server:
  port: 10086

spring:
  application:
    name: leyou-registry

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka  #配置客户端服务的url
    register-with-eureka: false #设置为false，启动服务时，将不会自己吧自己注册成服务
    fetch-registry: false   #不需要拉取服务
  server:
    eviction-interval-timer-in-ms: 1000
    enable-self-preservation: false