server:
  port: 8089
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql:///leyou
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.5.9
  rabbitmq:
    virtual-host: /
    host: 192.168.5.9
    username: leyou
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.user.pojo