server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/leyou?characterEncoding=utf-8&serverTimezone=UTC
    username: root
  rabbitmq:
    host: 192.168.5.9
    username: leyou
    password: 123456
    virtual-host: /
    template:
      exchange: LEYOU.ITEM.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.item.pojo
  configuration:
    map-underscore-to-camel-case: true  #使用通用mapper自定义的方法要开启驼峰命名法


